-- MySQL Script generated by MySQL Workbench
-- 12/16/16 19:30:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema elibrary
-- -----------------------------------------------------
-- WSD 2016
-- 

-- -----------------------------------------------------
-- Schema elibrary
--
-- WSD 2016
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elibrary` DEFAULT CHARACTER SET utf8 ;
USE `elibrary` ;

-- -----------------------------------------------------
-- Table `elibrary`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elibrary`.`Users` (
  `idUsers` INT NOT NULL,
  `Login` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `Adress` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `elibrary`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elibrary`.`Books` (
  `idBooks` INT NOT NULL,
  `Title` VARCHAR(45) NULL,
  `Author` VARCHAR(45) NULL,
  `Sygnature` INT NULL,
  `Price` DOUBLE NULL,
  `ISBN` VARCHAR(13) NULL,
  `Year` INT(4) NULL,
  `Weight` INT NULL,
  PRIMARY KEY (`idBooks`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elibrary`.`Users_uptakes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elibrary`.`Users_uptakes` (
  `idUsers_uptakes` INT NOT NULL,
  `Start_time` DATE NULL,
  `End_time` DATE NULL,
  `Users_idUsers` INT NOT NULL,
  `Books_idBooks` INT NOT NULL,
  PRIMARY KEY (`idUsers_uptakes`),
  INDEX `fk_Users_uptakes_Users1_idx` (`Users_idUsers` ASC),
  INDEX `fk_Users_uptakes_Books1_idx` (`Books_idBooks` ASC),
  CONSTRAINT `fk_Users_uptakes_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `elibrary`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_uptakes_Books1`
    FOREIGN KEY (`Books_idBooks`)
    REFERENCES `elibrary`.`Books` (`idBooks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elibrary`.`Drone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elibrary`.`Drone` (
  `idDrone` INT NOT NULL,
  `Producent` VARCHAR(45) NULL,
  `Active` TINYINT(1) NULL,
  `Actual position` VARCHAR(45) NULL,
  `Work_status` VARCHAR(45) NULL,
  PRIMARY KEY (`idDrone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elibrary`.`Libraries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elibrary`.`Libraries` (
  `idLibraries` INT NOT NULL,
  `status` TINYINT(1) NULL,
  `Location` VARCHAR(45) NULL,
  `Drone_idDrone` INT NOT NULL,
  PRIMARY KEY (`idLibraries`, `Drone_idDrone`),
  INDEX `fk_Libraries_Drone1_idx` (`Drone_idDrone` ASC),
  CONSTRAINT `fk_Libraries_Drone1`
    FOREIGN KEY (`Drone_idDrone`)
    REFERENCES `elibrary`.`Drone` (`idDrone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elibrary`.`Library_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elibrary`.`Library_books` (
  `idLibrary_books` INT NOT NULL,
  `Libraries_idLibraries` INT NOT NULL,
  `Books_idBooks` INT NOT NULL,
  `Avaliable` TINYINT(1) NULL,
  `Library_bookscol` VARCHAR(45) NULL,
  PRIMARY KEY (`idLibrary_books`),
  INDEX `fk_Library_books_Libraries1_idx` (`Libraries_idLibraries` ASC),
  INDEX `fk_Library_books_Books1_idx` (`Books_idBooks` ASC),
  CONSTRAINT `fk_Library_books_Libraries1`
    FOREIGN KEY (`Libraries_idLibraries`)
    REFERENCES `elibrary`.`Libraries` (`idLibraries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Library_books_Books1`
    FOREIGN KEY (`Books_idBooks`)
    REFERENCES `elibrary`.`Books` (`idBooks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elibrary`.`User_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elibrary`.`User_account` (
  `idUser_account` INT NOT NULL,
  `RFID_card` INT NULL,
  `ballance` DOUBLE NULL,
  `User_accountcol1` VARCHAR(45) NULL,
  `Users_idUsers` INT NOT NULL,
  PRIMARY KEY (`idUser_account`),
  INDEX `fk_User_account_Users1_idx` (`Users_idUsers` ASC),
  CONSTRAINT `fk_User_account_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `elibrary`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elibrary`.`User_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elibrary`.`User_payment` (
  `idUser_payment` INT NOT NULL,
  `Amount` VARCHAR(45) NULL,
  `Date` DATE NULL,
  `Users_idUsers` INT NOT NULL,
  PRIMARY KEY (`idUser_payment`),
  INDEX `fk_User_payment_Users1_idx` (`Users_idUsers` ASC),
  CONSTRAINT `fk_User_payment_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `elibrary`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
